# Generated by Django 5.1.4 on 2024-12-07 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_metric"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=1000)),
                ("content_type", models.CharField(max_length=255)),
                ("size", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="metric",
            name="core_metric_run_id_33ae87_idx",
        ),
        migrations.AddField(
            model_name="metric",
            name="metric_type",
            field=models.CharField(
                choices=[("metric", "Metric"), ("param", "Parameter")],
                default="param",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="metric",
            index=models.Index(
                fields=["run", "key", "metric_type"],
                name="core_metric_run_id_7f0e4a_idx",
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="core.run",
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["run", "name"], name="core_artifa_run_id_0744cd_idx"
            ),
        ),
    ]
